export const SET_MERC_LIBRARY = "set_merc_library"
export const GET_MERC_LIBRARY = "get_merc_library"
export const ADD_MERC_TO_COLLECTION = "add_merc_to_collection"
export const GET_COLLECTED_MERC = "get_collected_merc"
export const ABILITY_INCREMENT = "ability_increment"
export const ABILITY_DECREMENT = "ability_decrement"
export const ITEM_INCREMENT = "item_increment"
export const ITEM_DECREMENT = "item_decrement"
export const TASK_INCREMENT = "task_increment"
export const TASK_DECREMENT = "task_decrement"

